# Generated by Django 3.1.4 on 2022-07-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_api', '0002_alter_link_original_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='link',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
