# Generated by Django 3.1.4 on 2022-07-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_api', '0003_auto_20220715_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='custom_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
