# Generated by Django 3.1.4 on 2022-07-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener_api', '0004_link_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='custom_url',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
